#version 460

#extension GL_EXT_ray_tracing : require

layout(binding = 0, set = 0, rgba32f) uniform image2D output_image;
layout(binding = 1, set = 0) uniform sampler2D in_normal;
layout(binding = 2, set = 0) uniform sampler2D in_position;

void main()
{
    ivec2 p = ivec2(gl_LaunchIDEXT.xy);
    vec3 normal = texelFetch(in_normal, p, 0).rgb;
    imageStore(output_image, p, vec4(normal * 0.5 + 0.5, 1.0));
}